name: Modern App Lint

on:
  push:
    branches:
      - Dev
    paths:
      - modern/**
  pull_request:
    branches:
      - Dev
    paths:
      - modern/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        cache: npm
        cache-dependency-path: modern/package-lock.json
    - run: npm ci
      working-directory: modern
    - run: npm run lint
      working-directory: modern
